#!/usr/bin/env node
var dir = process.argv[2];
var app = dir + "/app";
var fs = require('fs-extra');
var shell = require('shelljs');

if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir);
}

console.log(`building '${dir}'...`);

fs.copy('./template', dir, (err) => {
    if (err) {
        return console.log(err);
    }

    shell.exec(`cd ${dir} && npm i`);

    console.log(`northwest app '${dir}' built`);
});
