#!/usr/bin/env node
var dir = process.argv[2];
var app = dir + "/app";
var fs = require('fs');
var copydir = require('copy-dir');
var shell = require('shelljs');

if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir);
}

console.log(`building '${dir}'...`);

copydir.sync('./template', dir);
shell.exec(`cd ${dir} && npm i`);

console.log(`northwest app '${dir}' built`);
